# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('excerpt', models.CharField(blank=True, max_length=200, verbose_name='简介')),
                ('content', django_markdown.models.MarkdownField(verbose_name='内容')),
                ('create_time', models.DateTimeField(verbose_name='建立时间')),
                ('modified_time', models.DateTimeField(verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '文章',
                'db_table': 'Article',
                'verbose_name_plural': '文章s',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
                'db_table': 'Category',
                'verbose_name_plural': '分类s',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'db_table': 'Tag',
                'verbose_name_plural': '标签s',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag', verbose_name='标签'),
        ),
    ]
